# Generated by Django 3.2.16 on 2023-02-19 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20230219_0457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_3',
        ),
    ]
