# Generated by Django 3.2.16 on 2023-02-11 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multilang', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='multilang',
            name='msg_id',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='multilang',
            name='en_us',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='multilang',
            name='zh_hans',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='multilang',
            name='zh_hant',
            field=models.TextField(null=True),
        ),
    ]
