# Generated by Django 3.2.16 on 2023-02-16 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multilang', '0002_auto_20230211_0338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multilang',
            name='en_us',
            field=models.TextField(default='', null=True),
        ),
    ]
