# Generated by Django 3.2.16 on 2023-02-16 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multilang', '0003_alter_multilang_en_us'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multilang',
            name='en_us',
            field=models.TextField(null=True),
        ),
    ]
