# Generated by Django 3.2.16 on 2023-02-21 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multilang', '0004_alter_multilang_en_us'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multilang',
            name='en_us',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='multilang',
            name='zh_hans',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='multilang',
            name='zh_hant',
            field=models.TextField(blank=True, default=''),
        ),
    ]
