# Generated by Django 3.2.16 on 2023-02-21 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multilang', '0006_alter_multilang_zh_hans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multilang',
            name='zh_hant',
            field=models.TextField(blank=True),
        ),
    ]
